### ISSUE TITLE
Why is VOMS_SERVER_DN a list?

### ISSUE THREAD

**Issue by jrha** [quattor/template-library-grid#156]
It is written like a `dict` (or `nlist` given it's age), is this a typo or intentional?
It certainly makes it quite annoying to use.

**Comment by Pansanel** [comment]
You are right, it may have sense to be a dict. Michel or Guillaume, any ideas about this?

**Comment by jouvin** [comment]
I guess this is a typo... The problem is that this template is not used anywhere in the template library (probably useless) and then was never tested... Fixed.
Note that for me this template is maintained/generated by SCDB UpdateVOConfig task. This may require to fix it to avoid generating this buggy template... or may be just remove it.

**Comment by jrha** [comment]
We use it at RAL, but by changing it to a dict, it's quite useful.
